# Site settings
title: Sass Guidelines
description: "An opinionated styleguide for writing sane, maintainable and scalable Sass"
keywords: CSS, Sass, SCSS, styleguide, guidelines
baseurl: ""
url: "http://sass-guidelin.es"
twitter_username: HugoGiraudel
languages:
  - cz
  - da
  - de
  - el
  - en
  - es
  - fr
  - ko
  - pl
  - pt
  - ru
  - zh

# Build settings
safe: true
exclude: 
  - node_modules
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - TRANSLATING.md
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - .tmp
  - bin
  - assets/js/vendor/loadFont.js
  - assets/js/src
  - assets/js/bundle.js

markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..1

sass:
  sass_dir: ./assets/sass
  style: :compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  blanklines: false
  startings: []
