# Site settings
title: Sass Guidelines
description: >
  Styleguide for writing sane, maintainable and scalable Sass.
baseurl: ""
url: "http://sass-guidelin.es"
twitter_username: HugoGiraudel
github_username:  HugoGiraudel

# Build settings
markdown: kramdown
