# Site settings
title: Sass Guidelines
description: "An opinionated styleguide for writing sane, maintainable and scalable Sass"
keywords: CSS, Sass, SCSS, styleguide, guidelines
baseurl: ""
url: "http://sass-guidelin.es"
twitter_username: HugoGiraudel
github_username:  HugoGiraudel

# Build settings
markdown: kramdown

sass:
    style: :compressed
